language: python

sudo: false
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=cover

install:
    - travis_retry pip install tox==1.6.1

script:
    - travis_retry tox
notifications:
    email: false
